version: '3.8'

services:
  bot:
    build: .
    container_name: subscription-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
